# Generated by Django 4.0.1 on 2022-02-21 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='last_name',
        ),
        migrations.AddField(
            model_name='actor',
            name='full_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Полное имя'),
            preserve_default=False,
        ),
    ]
